config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'users/new'
  get 'users/create'
  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  enum status: { invited: 0, accepted: 1, refused: 2 }
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :enrollments
  has_many :attendee, through: :enrollments, source: :user

  scope :previous, -> { where('start_date > ?', Time.zone.today) }
  scope :future, -> { where('start_date < ?', Time.zone.today) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, inverse_of: 'creator', foreign_key: 'creator_id'
  has_many :enrollments
  has_many :attended_events, through: :enrollments, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find_by(id: params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:creator_id, :title, :start_date, :end_date, :start_time, :end_time, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %><br />
    <%= form.text_area :description, placeholder: "Enter a description of your event..." %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="top">
  <div class="section">
    <h2 class="title is-2">Upcoming Events</h2>
    <div class="columns">
      <% @events.future.each do |event| %>
        <div class="column is-3">
          <div class="card">
            <header class="card-header">
              <%= link_to event.name, event_path(event), class: "card-header-title is-centered" %>
            </header>
            <div class="card-content">
              <div class="content has-text-justified">
                <%= event.description.truncate_words(12) %>
              </div>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item is-narrow"><%= event.date %></p>
              <p class="card-footer-item"><%= event.location %></p>
            </footer>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="bottom">
  <div class="section">
    <h2 class="title is-2">Past Events</h2>
    <div class="columns">
      <% @events.previous.each do |event| %>
        <div class="column is-3">
          <div class="card">
            <header class="card-header">
              <%= link_to event.name, event_path(event), class: "card-header-title is-centered" %>
            </header>
            <div class="card-content">
              <div class="content has-text-justified">
                <%= event.description.truncate_words(12) %>
              </div>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item"><%= event.date %></p>
              <p class="card-footer-item"><%= event.location %></p>
            </footer>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="Block">
  <h4>Host: <%= @event.creator.username %></h4>
</div>

<div>
  <h6>Attendies:</h6>
  <ul>
    <% if User.find(@event.enrollments.accepted.map { |en| en.user_id }).any? %>
      <div>
        <% User.find(@event.enrollments.accepted.map { |en| en.user_id }).each do | user | %>
          <li><p><%= user.username %></p></li>
      </div>
  </ul>
</div>

<div>
  <h6>Invities:</h6>
  <ul>
    <% if User.find(@event.enrollments.invited.map { |en| en.user_id }).any? %>
      <div>
        <% User.find(@event.enrollments.accepted.map { |en| en.user_id }).each do | user | %>
          <li><p><%= user.username %></p></li>
      </div>
  </ul>
</div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="section">
  <div class="container">
	  <div class="columns is-centered">
      <div class="column is-9">
        <h1 class="title is-2 is-spaced has-text-centered"><%= @user.username %>'s Profile</h1>

        <div class="column has-text-centered">
          <h3 class="subtitle is-3">Upcoming Events: <%= @user.events.future.count %></h3>
          <ul>
            <% if @user.events.future.count.zero? %>
              <p>No upcoming events</p>
            <% else %>
              <% @user.attended_events.future.each do |event| %>
                <li class="has-text-centered"><%=link_to event.name, event_path(event) %></li>
              <% end %>
            <% end %>
          </ul>
        </div>

        <div class="column has-text-centered">
          <h3 class="subtitle is-3">Previous Attended Events: <%= @user.events.previous.count %></h3>
          <ul>
            <% if @user.events.previous.count.zero? %>
              <p>No previous events attended</p>
            <% else %>
              <% @user.attended_events.previous.each do |event| %>
                <li class="has-text-centered"><%=link_to event.name, event_path(event) %></li>
              <% end %>
            <% end %>
          </ul>
        </div>

        <div id="navbar" class="navbar">
          <p class="control">
          </p>
          <% if user_signed_in? %>
            <p class="control">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
       